<a href="https://colab.research.google.com/github/swatibhogesh/swatibhogesh/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

defining a list

In [2]:
ages_list = [2,14,38,26,45,22]
print(ages_list)

[2, 14, 38, 26, 45, 22]


To instantiate numpy array object.
np.array(list name)

In [3]:
ages = np.array(ages_list)

In [4]:
print(ages)
print(type(ages))

[ 2 14 38 26 45 22]
<class 'numpy.ndarray'>


To check size and shape of array

In [5]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[ 2 14 38 26 45 22]
Size:	 6
Shape:	 (6,)


In [7]:
number = ([2,6,7,9],[3,5,6,7])
num = np.array(number)
print(num)
print("shape of num:\t", num.shape)

[[2 6 7 9]
 [3 5 6 7]]
shape of num:	 (2, 4)


In [10]:
zeroArr = np.zeros(6)
#return a new array of given shape
print(zeroArr)

[0. 0. 0. 0. 0. 0.]


Multidimensional Array

New list containing weight of people

In [11]:
weight_list = [48,56,63,42,60,72]

Defining an array containing ages_list and weight list

In [14]:
people = np.array([ages_list,weight_list])
print("people:\t",people)

people:	 [[ 2 14 38 26 45 22]
 [48 56 63 42 60 72]]


In [15]:
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

Size:	 12
Shape:	 (2, 6)


Reshape array
(new size must be same size as old array)

In [16]:
people= people.reshape(12,1)
print("people:\t",people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

people:	 [[ 2]
 [14]
 [38]
 [26]
 [45]
 [22]
 [48]
 [56]
 [63]
 [42]
 [60]
 [72]]
Size:	 12
Shape:	 (12, 1)


In [17]:
people= people.reshape(3,4)
print("people:\t",people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

people:	 [[ 2 14 38 26]
 [45 22 48 56]
 [63 42 60 72]]
Size:	 12
Shape:	 (3, 4)


In [18]:
people= people.reshape(1,12)
print("people:\t",people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

people:	 [[ 2 14 38 26 45 22 48 56 63 42 60 72]]
Size:	 12
Shape:	 (1, 12)


EXCERCISE

1. Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

In [25]:
values=[7,9,65,33,85,99]
arrvalues= np.array(values)
print("1D numpy array:\t",arrvalues)
print("size:\t",arrvalues.size)
print("shape:\t",arrvalues.shape)

1D numpy array:	 [ 7  9 65 33 85 99]
size:	 6
shape:	 (6,)


2.Generate a matrix (2D numpy array) of the values

In [24]:
values=[1,2,4,2,3,0,0,5,1]
arrvalues= np.array(values)
arrvalues= arrvalues.reshape(3,3)
print(arrvalues)
print("size:\t",arrvalues.size)
print("shape:\t",arrvalues.shape)

[[1 2 4]
 [2 3 0]
 [0 5 1]]
size:	 9
shape:	 (3, 3)


3.Change the dimensions of this array to another permitted shape

In [26]:
values=[1,2,4,2,3,0,0,5,1]
arrvalues= np.array(values)
arrvalues= arrvalues.reshape(9,1)
print(arrvalues)
print("size:\t",arrvalues.size)
print("shape:\t",arrvalues.shape)

[[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]
size:	 9
shape:	 (9, 1)


In [27]:
values=[1,2,4,2,3,0,0,5,1]
arrvalues= np.array(values)
arrvalues= arrvalues.reshape(1,9)
print(arrvalues)
print("size:\t",arrvalues.size)
print("shape:\t",arrvalues.shape)

[[1 2 4 2 3 0 0 5 1]]
size:	 9
shape:	 (1, 9)


ARRAY GENERATION

np.arange() method:
The np.arange() method creates a range of numbers with user defined steps between each.

In [28]:
five_times_table = np.arange(0, 55, 5)
print(five_times_table)
#np.arange method: numpy.arange([start, ]stop, [step, ], dtype=None)
#start is the number (integer or decimal) that defines the first value in the array.
#stop is the number that defines the end of the array and isn’t included in the array.
#step is the number that defines the difference between each two consecutive values in the array and defaults to 1.
#dtype is the type of the elements of the output array and defaults to None.

[ 0  5 10 15 20 25 30 35 40 45 50]


np.linspace() method: The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [29]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [30]:
#the endpoint of interval can optionally be excluded by making endpoint false
five_spaced = np.linspace(0,50,11,endpoint=False)
print(five_spaced)


[ 0.          4.54545455  9.09090909 13.63636364 18.18181818 22.72727273
 27.27272727 31.81818182 36.36363636 40.90909091 45.45454545]


np.repeat() method: The .repeat() method will repeat an object you pass a specified number of times.

In [32]:
twoArr = np.repeat(2, 10)
#it will repeat number '2' ten times
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


In [33]:
twoArr = np.repeat(7, 20)
print(twoArr)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


np.eye() method: The np.eye() functions will create an identity matrix/array for us.

In [34]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


OPERATIONS

In [36]:
print(five_times_table)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [35]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


SPEED TEST

In [37]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [38]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [39]:
%timeit five_times_table_lge + 5

1.43 µs ± 288 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [40]:
%timeit [e + 5 for e in fives_list]

59.8 µs ± 611 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

TRANSPOSE

In [42]:
people

array([[ 2, 14, 38, 26, 45, 22, 48, 56, 63, 42, 60, 72]])

In [43]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[ 2 14 38 26 45 22]
 [48 56 63 42 60 72]] 

[[ 2 48]
 [14 56]
 [38 63]
 [26 42]
 [45 60]
 [22 72]]


DATA TYPES

In [44]:
people.dtype

dtype('int64')

In [50]:
#What is the data type of the below ndarray?
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings.dtype
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [49]:
#What is the dtype of this array?
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [51]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
ages_with_strings.dtype = 'int32'
print(ages_with_strings)


['10' '5' '8' '32' '65' '43']
[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [52]:
ages_with_strings.size

126

In [53]:
ages_with_strings.size/21

6.0

In [54]:
np.array([10, 5, 8, '32', '65', '43']).size

6

astype()method

In [55]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


EXCERCISE

1. Create an array of string numbers, but use dtype to make it an array of floats.

In [59]:
numbers_strings = np.array(['2','23','56','12','76'],dtype='float')
print(numbers_strings)

[ 2. 23. 56. 12. 76.]


2.Transpose the matrix, printing the new size and shape.

In [62]:
matrix = np.array([2,3,5,6,98,67,4,14,74,80,8,63])
matrix.shape = (2, 6)
print(matrix, "\n")
print(matrix.T)

[[ 2  3  5  6 98 67]
 [ 4 14 74 80  8 63]] 

[[ 2  4]
 [ 3 14]
 [ 5 74]
 [ 6 80]
 [98  8]
 [67 63]]


3. Use the .astype() method to convert the array to boolean.

In [112]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('bool'))

['10' '5' '8' '32' '65' '43']
[ True  True  True  True  True  True]


ARRAY SLICING OPERATIONS

In [64]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [65]:
five_times_table[0]

0

In [66]:
five_times_table[-1]

50

In [67]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [68]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [69]:
print(people)
people[:3, :3]

[[ 2 14 38 26 45 22]
 [48 56 63 42 60 72]]


array([[ 2, 14, 38],
       [48, 56, 63]])

EXCERCISE

1. Create a numpy array with 50 zeros

In [70]:
zeroArr = np.zeros(50)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


2. Create a np array of 2 repeated 20 times

In [71]:
number= np.array([2,4])
print("20times:", 20 * number)

20times: [40 80]


Create a numpy array from 0 to 2pi in steps of 0.1

In [73]:
number = np.arange(0, 6.28, 0.1)
print(number)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]


First five values

In [108]:
number[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

Last 3 values

In [ ]:
number[-3:]

Get 4th to 7th value

In [109]:
number[3:6]

array([0.3, 0.4, 0.5])

n.flip() method

In [74]:
print(five_times_table)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [75]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

:: operator

In [79]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)

[50 45 40 35 30 25 20 15 10  5  0]


In [80]:
five_times_table[0::3]

array([ 0, 15, 30, 45])

EXCERCISE

Reverse it

In [83]:
people= people.reshape(1,12)
people

array([[ 2, 14, 38, 26, 45, 22, 48, 56, 63, 42, 60, 72]])

In [84]:
reverse_people = np.flip(people)
reverse_people

array([[72, 60, 42, 63, 56, 48, 22, 45, 26, 38, 14,  2]])

2. Only keep every 4th element

In [110]:
print(number[0::4])

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4.  4.4 4.8 5.2 5.6 6. ]


Get every 2nd element, starting from the last and moving backwards.

In [111]:
print(number[::2])

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2]


STATS

In [85]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [87]:
nums = np.arange(0, 4, 0.2555)
print(nums)

[0.     0.2555 0.511  0.7665 1.022  1.2775 1.533  1.7885 2.044  2.2995
 2.555  2.8105 3.066  3.3215 3.577  3.8325]


EXCERCISE

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [88]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


RANDOM

np.random() method

In [89]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [90]:
np.random.rand(10,20,9)

array([[[0.87609178, 0.68481183, 0.77324018, ..., 0.03153006,
         0.66273262, 0.77481439],
        [0.26398667, 0.20159606, 0.23109179, ..., 0.72484591,
         0.04977993, 0.76579567],
        [0.2290348 , 0.94753694, 0.69338081, ..., 0.14733096,
         0.38398946, 0.49143629],
        ...,
        [0.16380327, 0.75642951, 0.03099865, ..., 0.80037639,
         0.04776116, 0.10498047],
        [0.81505706, 0.03688695, 0.97456409, ..., 0.92767197,
         0.0042897 , 0.61847471],
        [0.63538862, 0.65661251, 0.77938261, ..., 0.88807911,
         0.73353463, 0.22544205]],

       [[0.2126993 , 0.99317236, 0.77200399, ..., 0.88940142,
         0.34817182, 0.33980209],
        [0.39899175, 0.54269738, 0.06988179, ..., 0.03512705,
         0.26348985, 0.17263749],
        [0.22419025, 0.14864161, 0.03752379, ..., 0.36436306,
         0.4092582 , 0.3170334 ],
        ...,
        [0.8236508 , 0.28131676, 0.05229028, ..., 0.19295798,
         0.77462211, 0.20546431],
        [0.1

np.random.normal()

In [92]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([ 3.52367263e-03, -6.68266886e-02, -1.81941389e-01, -1.27899076e-01,
       -2.47743801e-02, -1.05866324e-01,  2.89742906e-01, -1.99296220e-02,
        7.38136586e-02,  2.06647639e-01, -6.04819942e-02,  1.00939744e-02,
       -2.72930406e-02,  1.14464042e-01, -5.49284331e-02, -2.56247106e-01,
        7.32398654e-02,  1.81891183e-01, -1.19929730e-01,  2.86200674e-02,
       -2.50412740e-02,  1.12671088e-01, -2.10197988e-01,  8.31503314e-02,
       -9.20013388e-02,  1.68830843e-01, -1.84699801e-02, -1.67449817e-02,
       -1.98462881e-02,  1.54551659e-01,  1.16033411e-02, -4.89886182e-02,
       -8.18789486e-03,  1.54199701e-01,  2.34161011e-02,  1.73501230e-01,
        3.97079078e-02,  8.21443023e-02,  6.98471768e-03,  2.73182148e-02,
        9.80690186e-02, -3.90958322e-03, -1.19549842e-01,  9.07212735e-02,
        5.59083940e-02,  1.52655905e-01, -1.30261784e-01, -4.20076104e-02,
       -2.20410713e-02, -8.49120914e-02, -1.63337141e-02, -1.27003314e-01,
        1.55871890e-02, -

EXCERCISE

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

In [113]:
dice_six = np.random.choice([1,2,3,4,5,6],10)
dice_six

array([4, 3, 2, 6, 5, 4, 5, 4, 6, 3])

Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [97]:
coin_throw = np.random.choice(['Head',"Head",'Tail'],10)
coin_throw

array(['Head', 'Head', 'Tail', 'Head', 'Head', 'Tail', 'Head', 'Head',
       'Tail', 'Head'], dtype='<U4')